/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ventasdao.controladores.ClienteControlador;
import ventasdao.controladores.TipoClienteControlador;
import ventasdao.objetos.Cliente;
import ventasdao.objetos.TipoCliente;
import ventasdao.ui.grilla.GrillaCliente;

/**
 *
 * @author Hugo Chanampe
 */
public class AbmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmCliente
     */
    private Cliente cliente;
    private GrillaCliente grillaCliente;
    private ClienteControlador clienteControlador;
    private TipoClienteControlador tipoClienteControlador;
    private DefaultComboBoxModel modelCombo;
    
    public AbmCliente() {
        initComponents();
        
        clienteControlador = new ClienteControlador();
        tipoClienteControlador = new TipoClienteControlador();
        ArrayList<Cliente> clientes = new ArrayList<>();
        
        try {
            ArrayList<TipoCliente> tiposCliente = (ArrayList<TipoCliente>) tipoClienteControlador.listar();
            modelCombo = new DefaultComboBoxModel(tiposCliente.toArray());
            jcbTiposCliente.setModel(modelCombo);
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            clientes = clienteControlador.listar();
        } catch (Exception e) {
            e.printStackTrace ();
        }


        grillaCliente = new GrillaCliente(clientes);
        jtListadoCliente.setModel(grillaCliente);
    }
    
    public void limpiarCampos(){
        jtfNombre.setText("");
        jtfApellido.setText("");
        jtfDocumento.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfDocumento = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoCliente = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jbModificarCliente = new javax.swing.JButton();
        jbBajasCliente = new javax.swing.JButton();
        jbAltaCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbTiposCliente = new javax.swing.JComboBox<>();

        setClosable(true);

        jtfDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDocumentoKeyTyped(evt);
            }
        });

        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        jtfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfApellidoKeyTyped(evt);
            }
        });

        jLabel1.setText("Documento");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jtListadoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoCliente);

        jLabel4.setText("ID");

        jtfId.setEnabled(false);
        jtfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdActionPerformed(evt);
            }
        });

        jbModificarCliente.setText("Modificar");
        jbModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarClienteActionPerformed(evt);
            }
        });

        jbBajasCliente.setText("Eliminar");
        jbBajasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajasClienteActionPerformed(evt);
            }
        });

        jbAltaCliente.setText("Agregar");
        jbAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo Cliente");

        jcbTiposCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDocumento)
                            .addComponent(jtfNombre)
                            .addComponent(jtfApellido)
                            .addComponent(jtfId)
                            .addComponent(jcbTiposCliente, 0, 135, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jbAltaCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jbModificarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jbBajasCliente)
                        .addGap(59, 59, 59)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbTiposCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAltaCliente)
                            .addComponent(jbModificarCliente)
                            .addComponent(jbBajasCliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtListadoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoClienteMouseClicked
        // TODO add your handling code here:
        Cliente cliente = grillaCliente.getClienteFromRow(jtListadoCliente.getSelectedRow());
        
        jtfDocumento.setText(cliente.getDocumento());
        jtfApellido.setText(cliente.getApellido());
        jtfNombre.setText(cliente.getNombre());
        jtfId.setText(cliente.getId().toString());
    }//GEN-LAST:event_jtListadoClienteMouseClicked

    private void jbAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaClienteActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente();
        
        cliente.setNombre(jtfNombre.getText());
        cliente.setDocumento(jtfDocumento.getText());
        cliente.setApellido(jtfApellido.getText());
        cliente.setTipoCliente((TipoCliente) jcbTiposCliente.getSelectedItem());
        
        try {
            clienteControlador.crear(cliente);
            limpiarCampos();
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoCliente.setModel(new GrillaCliente(clienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAltaClienteActionPerformed

    private void jbModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarClienteActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente();
        
        cliente.setNombre(jtfNombre.getText());
        cliente.setDocumento(jtfDocumento.getText());
        cliente.setApellido(jtfApellido.getText());
        cliente.setTipoCliente((TipoCliente) jcbTiposCliente.getSelectedItem());
        cliente.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            clienteControlador.modificar(cliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoCliente.setModel(new GrillaCliente(clienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbModificarClienteActionPerformed

    private void jbBajasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajasClienteActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente();
        
        cliente.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            clienteControlador.eliminar(cliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoCliente.setModel(new GrillaCliente(clienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbBajasClienteActionPerformed

    private void jtfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdActionPerformed

    private void jtfDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDocumentoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        int limit = 8;
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Este campo solo admite numeros");
        }
        if((jtfDocumento.getText().length()) == (limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "DNI debe tener 8 caracteres");
        }
    }//GEN-LAST:event_jtfDocumentoKeyTyped

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Este campo solo admite letras");
        }
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Este campo solo admite letras");
        }
    }//GEN-LAST:event_jtfApellidoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaCliente;
    private javax.swing.JButton jbBajasCliente;
    private javax.swing.JButton jbModificarCliente;
    private javax.swing.JComboBox<String> jcbTiposCliente;
    private javax.swing.JTable jtListadoCliente;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfDocumento;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
