/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import ventasdao.controladores.ControladorProducto;
import ventasdao.controladores.DetalleFacturaControlador;
import ventasdao.controladores.FacturaControlador;
import ventasdao.objetos.DetalleFactura;
import ventasdao.objetos.Factura;
import ventasdao.objetos.Producto;
import ventasdao.ui.Principal;
import ventasdao.ui.grilla.GrillaDetalleFactura;

/**
 *
 * @author Crist
 */
public class AbmDetalleFactura extends javax.swing.JInternalFrame {

    private DetalleFactura detalleFactura;
    private DetalleFacturaControlador detalleFacturaControlador;
    private GrillaDetalleFactura grillaDetalleFactura;
    private ControladorProducto productoControlador;
    private FacturaControlador facturaControlador;
    private DefaultComboBoxModel modelCombo;

    /**
     * Creates new form AbmDetalleFactura
     */
    public AbmDetalleFactura() {
        initComponents();

        detalleFacturaControlador = new DetalleFacturaControlador();
        productoControlador = new ControladorProducto();
        ArrayList<DetalleFactura> detallesFactura = new ArrayList();

        try {
            ArrayList<Producto> productos = productoControlador.listar();
            modelCombo = new DefaultComboBoxModel(productos.toArray());
            jcbProducto.setModel(modelCombo);
        } catch (Exception ex) {
            Logger.getLogger(AbmDetalleFactura.class.getName()).log(Level.SEVERE, null, ex);
        }

        grillaDetalleFactura = new GrillaDetalleFactura(detallesFactura);
        jtListadoDetalleFactura.setModel(grillaDetalleFactura);
    }

    public void limpiarCampos() {
        jtfCantidad.setText("");
        jtfMonto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoDetalleFactura = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfCantidad = new javax.swing.JTextField();
        jtfMonto = new javax.swing.JTextField();
        jcbProducto = new javax.swing.JComboBox<>();
        jbAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGenerarFactura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Producto");

        jtListadoDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtListadoDetalleFactura);

        jLabel2.setText("Cantidad");

        jLabel3.setText("Monto");

        jtfCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCantidadActionPerformed(evt);
            }
        });

        jtfMonto.setDragEnabled(true);

        jcbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbGenerarFactura.setText("Generar Factura");
        jbGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarFacturaActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        jtfId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCantidad)
                            .addComponent(jtfMonto)
                            .addComponent(jcbProducto, 0, 135, Short.MAX_VALUE)
                            .addComponent(jtfId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(jbModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jbEliminar)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAgregar)
                            .addComponent(jbModificar)
                            .addComponent(jbEliminar))
                        .addGap(18, 18, 18)
                        .addComponent(jbGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCantidadActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        detalleFactura = new DetalleFactura();

        detalleFactura.setCantidad(Integer.parseInt(jtfCantidad.getText()));
        detalleFactura.setMonto(Float.parseFloat(jtfMonto.getText()));
        detalleFactura.setProducto((Producto) jcbProducto.getSelectedItem());

        try {
            detalleFacturaControlador.crear(detalleFactura);
        } catch (Exception ex) {
            Logger.getLogger(AbmDetalleFactura.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoDetalleFactura.setModel(new GrillaDetalleFactura((ArrayList<DetalleFactura>) detalleFacturaControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmDetalleFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        detalleFactura = new DetalleFactura();

        detalleFactura.setProducto((Producto) jcbProducto.getSelectedItem());
        detalleFactura.setCantidad(Integer.parseInt(jtfCantidad.getText()));
        detalleFactura.setMonto(Float.parseFloat(jtfMonto.getText()));
        
        try {
            detalleFacturaControlador.modificar(detalleFactura);
        } catch (Exception ex) {
            Logger.getLogger(AbmDetalleFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            jtListadoDetalleFactura.setModel(new GrillaDetalleFactura((ArrayList<DetalleFactura>) detalleFacturaControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmDetalleFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        detalleFactura = new DetalleFactura();
        
        detalleFactura.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            detalleFacturaControlador.eliminar(detalleFactura);
        } catch (Exception ex) {
            Logger.getLogger(AbmDetalleFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            jtListadoDetalleFactura.setModel(new GrillaDetalleFactura((ArrayList<DetalleFactura>) detalleFacturaControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmDetalleFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarFacturaActionPerformed
        // TODO add your handling code here:
        AbmFactura abmFactura = new AbmFactura();
        Principal.jdpContenedorPrincipal.add(abmFactura);
        
        abmFactura.toFront();
        abmFactura.setVisible(true);
    }//GEN-LAST:event_jbGenerarFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGenerarFactura;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbProducto;
    private javax.swing.JTable jtListadoDetalleFactura;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfMonto;
    // End of variables declaration//GEN-END:variables
}
